version: '3'

services:

  task-service:
    build: ./task-service
    ports:
      - "8000:8000"

  notification-service:
    build: ./notification-service
    ports:
      - "8001:8001"

  redis:
    image: redis
    ports:
      - "6379:6379"
